baseURL = "https://charoy.github.io/colladict/"
title = "Colladict"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

[params]
  githubRepository = "https://github.com/charoy/colladict"
  githubIssues = "https://github.com/charoy/colladict/issues"
  githubPulls = "https://github.com/charoy/colladict/pulls"

[permalinks]
  entries = "/entries/:slug/"

[taxonomies]
  theme = "themes"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    weight = 1
    [languages.en.params]
      subtitle = "A critical dictionary of CSCW"
      description = "A public, versioned, collaborative site for defining, historicising and debating key concepts in Computer-Supported Cooperative Work."
    [languages.en.permalinks]
      entries = "/entries/:slug/"
    [[languages.en.menu.main]]
      name = "Home"
      pageRef = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Entries"
      pageRef = "/entries"
      weight = 2
    [[languages.en.menu.main]]
      name = "Method"
      pageRef = "/methodology"
      weight = 3
    [[languages.en.menu.main]]
      name = "Contribute"
      pageRef = "/contribute"
      weight = 4

  [languages.fr]
    languageCode = "fr-FR"
    languageName = "Français"
    weight = 2
    [languages.fr.params]
      subtitle = "Un dictionnaire critique du CSCW"
      description = "Un site public, versionné et contributif pour définir, historiciser et discuter les concepts du Computer-Supported Cooperative Work."
    [languages.fr.permalinks]
      entries = "/entrees/:slug/"
    [[languages.fr.menu.main]]
      name = "Accueil"
      pageRef = "/"
      weight = 1
    [[languages.fr.menu.main]]
      name = "Entrées"
      pageRef = "/entries"
      weight = 2
    [[languages.fr.menu.main]]
      name = "Méthode"
      pageRef = "/methodology"
      weight = 3
    [[languages.fr.menu.main]]
      name = "Contribuer"
      pageRef = "/contribute"
      weight = 4
